// Adaptive crowd: the home support gets louder the longer their team keeps the
// ball. Composes with the goal/danger driven excitement already computed in
// Match::UpdateCrowdAudio.
// See SIMULATION_IMPROVEMENT_PROPOSAL.md section 5A.

#ifndef _HPP_CROWD_MOOD
#define _HPP_CROWD_MOOD

namespace CrowdMood {

// Excitement an evenly balanced game generates on its own.
const float evenGameExcitement = 0.15f;
// How loud sustained home possession alone can get the crowd.
const float maxPossessionExcitement = 0.55f;

// Share of recent possession belonging to the home team, in [0, 1].
// `possessionFactor60s` follows MatchData::GetPossessionFactor_60seconds():
// 0 means team 0 has had all the ball, 1 means team 1 has.
float GetHomeSupportFactor(float possessionFactor60s, int homeTeamID);

// Crowd excitement generated by possession alone.
float GetPossessionExcitement(float possessionFactor60s, int homeTeamID);

// Folds possession excitement into the existing excitement level without ever
// quietening a crowd that is already louder.
float Blend(float baseExcitement, float possessionExcitement);

}  // namespace CrowdMood

#endif
