"""Classifies the recovered PES animation names into GF animation roles.

The PES grammar is <action>_<startSpeed>_<endSpeed>_<...modifiers...> with
speeds 0-4 and angle tokens (000/045/.../f180, yNN heights, ver/style
suffixes). This maps each of the 4,389 clips onto GameplayFootball's anim
vocabulary and writes a manifest CSV:

  name,family,gf_type,incoming_velocity,outgoing_velocity,angle

Families -> GF types:
  dm_goal_* / dm_miss_*             special (celebrations; installed already)
  dm_* other                        special (cutscene one-offs)
  assistant_* / referee_*           official
  gk* / dive / catch / punch        keeper
  kick / shoot / cross / longpass   ballcontrol:kick
  trap* / control                   ballcontrol:trap
  head*                             ballcontrol:header
  tackle* / sliding                 interfere
  run/walk/dash/jog/idle/turn/stop  movement
  feint* / js_*                     movement_special

Speeds: 0=idle, 1=dribble, 2=walk, 3/4=sprint (GF e_Velocity buckets).

NOTE: only the manifest is generated by default. Bulk-installing movement
anims replaces the tuned stock locomotion and needs playtesting;
--install-family <family> exists for experiments, writing GF metadata
tails (<type> + quantizedframetime) alongside.
"""

import argparse
import csv
import os
import re
import sys

SPEED_TO_VELOCITY = {0: "idle", 1: "dribble", 2: "walk", 3: "sprint", 4: "sprint"}

FAMILY_RULES = [
    (r"^dm_goal", ("celebration", "special")),
    (r"^dm_miss", ("dejection", "special")),
    (r"^dm_", ("cutscene", "special")),
    (r"^assistant|^referee", ("official", "official")),
    (r"^gk|^dive|^catchs?|^punch", ("keeper", "keeper")),
    (r"^kick|^shoot|^cross|^longpass|^volley", ("kick", "ballcontrol")),
    (r"^trap|^control", ("trap", "ballcontrol")),
    (r"^head", ("header", "ballcontrol")),
    (r"^tackle|^sliding|^slide", ("tackle", "interfere")),
    (r"^feint|^js_", ("feint", "movement_special")),
    (r"^run|^walk|^dash|^jog|^idle|^turn|^stop|^dribble", ("locomotion", "movement")),
]

SPEEDS = re.compile(r"_([0-4])_([0-4])(?:_|$)")
ANGLE = re.compile(r"_(?:f?)(\d{3})(?:_|$)")


def classify(name):
    family, gf_type = ("other", "unknown")
    for pattern, result in FAMILY_RULES:
        if re.search(pattern, name):
            family, gf_type = result
            break
    speeds = SPEEDS.search(name)
    vin = vout = ""
    if speeds:
        vin = SPEED_TO_VELOCITY[int(speeds.group(1))]
        vout = SPEED_TO_VELOCITY[int(speeds.group(2))]
    angle = ""
    angle_match = ANGLE.search(name)
    if angle_match:
        angle = angle_match.group(1)
    return family, gf_type, vin, vout, angle


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--names", default="anim_names.txt")
    parser.add_argument("--out", default="anim_manifest.csv")
    args = parser.parse_args()

    names = [l.strip() for l in open(args.names) if l.strip()]
    rows = [(n,) + classify(n) for n in names]
    with open(args.out, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["name", "family", "gf_type",
                    "incoming_velocity", "outgoing_velocity", "angle"])
        w.writerows(rows)

    from collections import Counter
    counts = Counter(r[1] for r in rows)
    print("classified %d anims -> %s" % (len(rows), args.out))
    for family, count in counts.most_common():
        print("  %-12s %d" % (family, count))


if __name__ == "__main__":
    main()
