"""Generates flat-outline crowds for an imported PES stadium.

PES's audiarea.bin (inside the stadium's audi fpk) lists each stand as a
sloped quad plus the row spacing the game itself uses (1.9m). This tool
turns every stand into rows of upright billboard strips textured with a
generated crowd-silhouette PNG - flat outlines, one draw-friendly
GEOMOBJECT, fully editable output (text ASE + PNG).

  python3 crowd_gen.py <audiarea.bin> <stadium_out_dir> [--name crowd]

Appends a <geometry> entry to the stadium's .object if one exists.
"""

import argparse
import math
import os
import random
import struct

import ase_util

ROW_MARKER = struct.pack("<f", 1.9)  # the row-step float; neighbours vary
PERSON_HEIGHT = 0.85
PERSON_WIDTH = 0.55


def parse_stands(path):
    """-> list of 4-corner stands (Fox coords), scanning for the row marker."""
    blob = open(path, "rb").read()
    stands = []
    at = 0
    while True:
        at = blob.find(ROW_MARKER, at)
        if at < 0:
            break
        corner_at = at + 12  # row step + two scale floats
        if corner_at + 48 <= len(blob):
            scales = struct.unpack_from("<2f", blob, at + 4)
            floats = struct.unpack_from("<12f", blob, corner_at)
            corners = [floats[i:i + 3] for i in range(0, 12, 3)]
            plausible = (all(0.5 < s < 2.0 for s in scales) and
                         all(all(abs(c) < 500 for c in p) for p in corners) and
                         any(any(abs(c) > 3 for c in p) for p in corners))
            if plausible:
                stands.append(corners)
        at += len(ROW_MARKER)
    return stands


def fox_to_gf(p):
    return (p[0], -p[2], p[1])


def rows_for_stand(corners, row_step=1.9):
    """Yields (row_start, row_end) GF points along the stand's slope."""
    c0, c1, c2, c3 = [fox_to_gf(p) for p in corners]
    # c0->c1 and c3->c2 are the slope edges (front to back)
    slope_len = math.dist(c0, c1)
    steps = max(1, int(slope_len / row_step))
    for i in range(steps + 1):
        t = i / steps if steps else 0.0
        a = tuple(c0[k] + (c1[k] - c0[k]) * t for k in range(3))
        b = tuple(c3[k] + (c2[k] - c3[k]) * t for k in range(3))
        yield a, b


def make_texture(path, columns=8, size=128):
    """Flat crowd-outline texture: dark silhouettes, transparent elsewhere."""
    from PIL import Image, ImageDraw
    rng = random.Random(60)
    img = Image.new("RGBA", (size * columns, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    for c in range(columns):
        x0 = c * size
        tint = rng.randint(18, 70)
        color = (tint, tint, tint + rng.randint(0, 25), 255)
        w = size * rng.uniform(0.62, 0.78)
        cx = x0 + size / 2 + rng.uniform(-6, 6)
        head_r = size * rng.uniform(0.13, 0.16)
        head_cy = size * rng.uniform(0.22, 0.28)
        # head
        draw.ellipse((cx - head_r, head_cy - head_r,
                      cx + head_r, head_cy + head_r), fill=color)
        # shoulders/torso
        top = head_cy + head_r * 0.7
        draw.rounded_rectangle((cx - w / 2, top, cx + w / 2, size),
                               radius=size * 0.18, fill=color)
    img.save(path)


def write_ase(stands, out_dir, name, bitmap_rel):
    quads = []
    for corners in stands:
        for a, b in rows_for_stand(corners):
            length = math.dist(a, b)
            if length < 1.0:
                continue
            up = (0.0, 0.0, PERSON_HEIGHT)
            quads.append((a, b,
                          tuple(b[k] + up[k] for k in range(3)),
                          tuple(a[k] + up[k] for k in range(3)),
                          length / PERSON_WIDTH))

    path = os.path.join(out_dir, name + ".ase")
    with open(path, "w") as out:
        out.write("*3DSMAX_ASCIIEXPORT\t200\n")
        out.write('*COMMENT "flat-outline crowd generated by tools/pes21_import"\n')
        out.write("*SCENE {\n\t*SCENE_FILENAME \"%s\"\n" % name)
        out.write("\t*SCENE_FIRSTFRAME 0\n\t*SCENE_LASTFRAME 100\n")
        out.write("\t*SCENE_FRAMESPEED 30\n\t*SCENE_TICKSPERFRAME 160\n")
        out.write("\t*SCENE_BACKGROUND_STATIC 0.000\t0.000\t0.000\n")
        out.write("\t*SCENE_AMBIENT_STATIC 0.000\t0.000\t0.000\n}\n")
        out.write("*MATERIAL_LIST {\n\t*MATERIAL_COUNT 1\n\t*MATERIAL 0 {\n")
        out.write('\t\t*MATERIAL_NAME "crowd"\n\t\t*MATERIAL_CLASS "Standard"\n')
        out.write("\t\t*MATERIAL_AMBIENT 0.588\t0.588\t0.588\n")
        out.write("\t\t*MATERIAL_DIFFUSE 0.588\t0.588\t0.588\n")
        out.write("\t\t*MATERIAL_SPECULAR 0.000\t0.000\t0.000\n")
        out.write("\t\t*MATERIAL_SHINE 0.010\n\t\t*MATERIAL_SHADING Blinn\n")
        out.write("\t\t*MATERIAL_SHINESTRENGTH 0.0\n")
        out.write("\t\t*MATERIAL_SELFILLUM 0.0\n")
        out.write("\t\t*MAP_DIFFUSE {\n\t\t\t*MAP_NAME \"crowd\"\n")
        out.write('\t\t\t*MAP_CLASS "Bitmap"\n')
        out.write('\t\t\t*BITMAP "%s"\n' % bitmap_rel)
        out.write("\t\t\t*MAP_TYPE Screen\n\t\t}\n\t}\n}\n")

        out.write("*GEOMOBJECT {\n")
        out.write('\t*NODE_NAME "crowd"\n')
        out.write("\t*NODE_TM {\n\t\t*NODE_NAME \"crowd\"\n")
        out.write("\t\t*INHERIT_POS 0 0 0\n\t\t*INHERIT_ROT 0 0 0\n\t\t*INHERIT_SCL 0 0 0\n")
        out.write("\t\t*TM_ROW0 1.0\t0.0\t0.0\n\t\t*TM_ROW1 0.0\t1.0\t0.0\n")
        out.write("\t\t*TM_ROW2 0.0\t0.0\t1.0\n\t\t*TM_ROW3 0.0\t0.0\t0.0\n\t}\n")
        out.write("\t*MESH {\n")
        out.write("\t\t*MESH_NUMVERTEX %d\n" % (len(quads) * 4))
        out.write("\t\t*MESH_NUMFACES %d\n" % (len(quads) * 2))
        out.write("\t\t*MESH_VERTEX_LIST {\n")
        for i, (a, b, c, d, _) in enumerate(quads):
            for j, p in enumerate((a, b, c, d)):
                out.write("\t\t\t*MESH_VERTEX %d\t%.3f\t%.3f\t%.3f\n"
                          % (i * 4 + j, p[0], p[1], p[2]))
        out.write("\t\t}\n\t\t*MESH_FACE_LIST {\n")
        for i in range(len(quads)):
            v = i * 4
            out.write("\t\t\t*MESH_FACE %d: A: %d B: %d C: %d AB: 1 BC: 1 CA: 1 "
                      "*MESH_SMOOTHING 1 *MESH_MTLID 0\n" % (i * 2, v, v + 1, v + 2))
            out.write("\t\t\t*MESH_FACE %d: A: %d B: %d C: %d AB: 1 BC: 1 CA: 1 "
                      "*MESH_SMOOTHING 1 *MESH_MTLID 0\n" % (i * 2 + 1, v, v + 2, v + 3))
        out.write("\t\t}\n")
        out.write("\t\t*MESH_NUMTVERTEX %d\n" % (len(quads) * 4))
        out.write("\t\t*MESH_TVERTLIST {\n")
        for i, (_, _, _, _, repeat) in enumerate(quads):
            for j, (u, v) in enumerate(((0, 0), (repeat, 0), (repeat, 1), (0, 1))):
                out.write("\t\t\t*MESH_TVERT %d\t%.2f\t%.2f\t0.0\n"
                          % (i * 4 + j, u, v))
        out.write("\t\t}\n")
        out.write("\t\t*MESH_NUMTVFACES %d\n" % (len(quads) * 2))
        out.write("\t\t*MESH_TFACELIST {\n")
        for i in range(len(quads)):
            v = i * 4
            out.write("\t\t\t*MESH_TFACE %d\t%d\t%d\t%d\n" % (i * 2, v, v + 1, v + 2))
            out.write("\t\t\t*MESH_TFACE %d\t%d\t%d\t%d\n" % (i * 2 + 1, v, v + 2, v + 3))
        out.write("\t\t}\n")
        all_verts = [p for (a, b, c, d, _) in quads for p in (a, b, c, d)]
        all_faces = []
        for i in range(len(quads)):
            v = i * 4
            all_faces.append((v, v + 1, v + 2))
            all_faces.append((v, v + 2, v + 3))
        ase_util.write_mesh_normals(out, all_verts, all_faces, smooth=False)
        out.write("\t}\n")
        out.write("\t*PROP_MOTIONBLUR 0\n\t*PROP_CASTSHADOW 0\n")
        out.write("\t*PROP_RECVSHADOW 0\n\t*MATERIAL_REF 0\n}\n")
    return path, len(quads)


GEOMETRY_ENTRY = """
	<geometry>
		<filename>%(name)s.ase</filename>
		<name>%(name)s</name>
		<position>0, 0, 0</position>
		<rotation>0, 0, 0, 0</rotation>
		<properties>
			<physicable>false</physicable>
			<movable>false</movable>
		</properties>
	</geometry>

</object>
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("audiarea")
    parser.add_argument("out_dir")
    parser.add_argument("--name", default="crowd")
    args = parser.parse_args()

    stands = parse_stands(args.audiarea)
    print("stands found:", len(stands))

    os.makedirs(args.out_dir, exist_ok=True)
    tex_path = os.path.join(args.out_dir, "textures", args.name + ".png")
    os.makedirs(os.path.dirname(tex_path), exist_ok=True)
    make_texture(tex_path)

    stadium = os.path.basename(os.path.normpath(args.out_dir))
    bitmap_rel = "media/objects/stadiums/%s/textures/%s.png" % (stadium, args.name)
    ase_path, quad_count = write_ase(stands, args.out_dir, args.name, bitmap_rel)
    print("wrote %s: %d crowd rows" % (ase_path, quad_count))

    # hook into the stadium object
    for entry in os.listdir(args.out_dir):
        if entry.endswith(".object"):
            obj_path = os.path.join(args.out_dir, entry)
            text = open(obj_path).read()
            if args.name + ".ase" not in text and "</object>" in text:
                text = text.replace("</object>", GEOMETRY_ENTRY % {"name": args.name})
                open(obj_path, "w").write(text)
                print("added crowd geometry to", obj_path)
