#!/usr/bin/env python3
"""Bake the PES21 in-match scoreboard theme into plain PNG + text assets.

Sources (tool inputs, never shipped):
  <extracted>/common/menu/licence/game2dPes/  - licence skin panel shapes.
      regions.json rects are in 2x space relative to the extracted PNGs.
      Panels encode shape in the R channel (0 = outside/border ring,
      224 = fill, antialiased in between); G/B/A are constant fillers.
  <extracted>/fonts/numMatch, fonts/numMid    - WFNT digit strips
      ('+', '-', '0'..'9') as white-on-alpha atlases + glyphs.json.

Outputs (simple editable formats, committed to the repo):
  data/media/ui/pes/scoreboard_bar.png   - wide navy bar (caps + stretched mid)
  data/media/ui/pes/clock_panel.png      - compact clock pill
  data/media/ui/pes/addedtime_panel.png  - crimson added-time chip
  data/media/ui/pes/num_match.png/.fnt   - score digits (bitmap font)
  data/media/ui/pes/num_mid.png/.fnt     - clock digits (bitmap font)

The .fnt format is a line-based text file:
  atlas <filename>
  line_height <px>
  ascent <px>
  glyph <codepoint> <x> <y> <w> <h> <bearing_x> <bearing_y> <advance>
A ':' glyph (missing from the num* strips) is synthesized from two square
dots, and ' ' is emitted as an advance-only glyph.
"""

import argparse
import json
import os

import numpy as np
from PIL import Image

DEFAULT_EXTRACTED = "/run/media/z/Dati III/PES21/extracted/ui"
DEFAULT_OUT = os.path.join(os.path.dirname(__file__), "..", "..",
                           "data", "media", "ui", "pes")

FILL_R = 224.0  # R-channel value of the panel fill plateau

# palettes: (top_rgb, bottom_rgb, alpha)
NAVY = ((38, 48, 84), (10, 14, 30), 216)
CRIMSON = ((150, 26, 36), (84, 8, 18), 224)


def load_region(skin_dir, index):
    regs = json.load(open(os.path.join(skin_dir, "regions.json")))
    reg = regs[index]
    tex = Image.open(os.path.join(skin_dir, "tex%03d.png" % reg["texture"]))
    arr = np.array(tex.convert("RGBA"))
    l, t, r, b = reg["rect"]
    scale = 2 if (r > tex.size[0] or b > tex.size[1]) else 1
    return arr[t // scale:b // scale, l // scale:r // scale]


def bake_panel(sub, palette):
    (top, bottom, alpha) = palette
    mask = np.clip(sub[:, :, 0].astype(np.float32) / FILL_R, 0.0, 1.0)
    h, w = mask.shape
    t = np.linspace(0.0, 1.0, h, dtype=np.float32)[:, None, None]
    grad = (1.0 - t) * np.array(top, np.float32) + t * np.array(bottom, np.float32)
    out = np.zeros((h, w, 4), np.uint8)
    out[:, :, :3] = np.round(np.broadcast_to(grad, (h, w, 3)))
    out[:, :, 3] = np.round(mask * alpha)
    return Image.fromarray(out, "RGBA")


def widen(img, target_w, cap_w):
    """Stretch a rounded panel to target_w keeping the corner caps crisp."""
    w, h = img.size
    if target_w <= w:
        return img
    left = img.crop((0, 0, cap_w, h))
    right = img.crop((w - cap_w, 0, w, h))
    mid = img.crop((cap_w, 0, w - cap_w, h)).resize(
        (target_w - 2 * cap_w, h), Image.BILINEAR)
    out = Image.new("RGBA", (target_w, h))
    out.paste(left, (0, 0))
    out.paste(mid, (cap_w, 0))
    out.paste(right, (target_w - cap_w, 0))
    return out


def export_font(font_dir, out_dir, base_name):
    meta = json.load(open(os.path.join(font_dir, "glyphs.json")))
    atlas = Image.open(os.path.join(font_dir, meta["atlases"][0])).convert("RGBA")
    line_height = meta["line_height"]
    ascent = meta["ascent"]
    glyphs = [g for g in meta["glyphs"] if g["char"] in "+-0123456789"]

    pad = 1
    # synthesized colon: two square dots
    dot = max(3, round(line_height * 0.16))
    colon_gap = max(2, round(line_height * 0.22))
    colon_h = dot * 2 + colon_gap
    colon_w = dot

    total_w = sum(g["w"] + pad for g in glyphs) + colon_w + 2 * pad
    out = Image.new("RGBA", (total_w, line_height + 2 * pad))
    lines = []
    lines.append("# PES21 %s bitmap font, regenerated by" % base_name)
    lines.append("# tools/pes21_import/export_scoreboard_theme.py")
    lines.append("atlas %s.png" % base_name)
    lines.append("line_height %d" % line_height)
    lines.append("ascent %d" % ascent)

    digit = next(g for g in glyphs if g["char"] == "0")
    # advance-only space, roughly a third of a digit cell
    lines.append("glyph 32 0 0 0 0 0 0 %d" % max(4, round(digit["advance"] * 0.42)))

    x = pad
    for g in sorted(glyphs, key=lambda g: g["code"]):
        cell = atlas.crop((g["x"], g["y"], g["x"] + g["w"], g["y"] + g["h"]))
        out.paste(cell, (x, pad))
        lines.append("glyph %d %d %d %d %d %d %d %d" % (
            g["code"], x, pad, g["w"], g["h"],
            g["bearing_x"], g["bearing_y"], g["advance"]))
        x += g["w"] + pad

    # colon
    colon = Image.new("RGBA", (colon_w, colon_h))
    square = Image.new("RGBA", (dot, dot), (255, 255, 255, 255))
    colon.paste(square, (0, 0))
    colon.paste(square, (0, colon_h - dot))
    out.paste(colon, (x, pad))
    colon_bearing_y = round(ascent * 0.72)
    lines.append("glyph 58 %d %d %d %d %d %d %d" % (
        x, pad, colon_w, colon_h,
        max(1, round(line_height * 0.06)), colon_bearing_y,
        colon_w + 2 * max(1, round(line_height * 0.06))))

    out.save(os.path.join(out_dir, base_name + ".png"))
    with open(os.path.join(out_dir, base_name + ".fnt"), "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote %s (.png %dx%d, %d glyphs)" % (
        os.path.join(out_dir, base_name), out.size[0], out.size[1],
        len(glyphs) + 2))


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--extracted", default=DEFAULT_EXTRACTED,
                    help="extracted dt11 ui root")
    ap.add_argument("-o", "--out", default=DEFAULT_OUT)
    args = ap.parse_args()

    out_dir = os.path.abspath(args.out)
    os.makedirs(out_dir, exist_ok=True)
    skin = os.path.join(args.extracted, "common", "menu", "licence", "game2dPes")

    # region 12: 1541x197 main bar; widen so 3-letter names + score fit.
    bar = bake_panel(load_region(skin, 12), NAVY)
    bar = widen(bar, 2000, 90)
    bar.save(os.path.join(out_dir, "scoreboard_bar.png"))
    print("wrote scoreboard_bar.png %dx%d" % bar.size)

    # region 19: 137x41 pill; widen a touch for "45:00".
    clock = bake_panel(load_region(skin, 19), NAVY)
    clock = widen(clock, 160, 18)
    clock.save(os.path.join(out_dir, "clock_panel.png"))
    print("wrote clock_panel.png %dx%d" % clock.size)

    chip = bake_panel(load_region(skin, 19), CRIMSON)
    chip = widen(chip, 150, 18)
    chip.save(os.path.join(out_dir, "addedtime_panel.png"))
    print("wrote addedtime_panel.png %dx%d" % chip.size)

    fonts = os.path.join(args.extracted, "fonts")
    export_font(os.path.join(fonts, "numMatch"), out_dir, "num_match")
    export_font(os.path.join(fonts, "numMid"), out_dir, "num_mid")


if __name__ == "__main__":
    main()
