"""Generates a sky dome for match scenes: an inward-facing hemisphere ASE
plus gradient+cloud textures (day / evening / night), killing the void
behind imported stadiums.

  python3 skydome_gen.py <out_dir>   # e.g. data/media/objects/stadiums/sky

Emits sky.object referencing sky.ase with textures/sky_day.png; the engine
picks the file via the "skydome_object" config key.
"""

import math
import os
import random
import sys

import ase_util

RADIUS = 320.0
RINGS = 10
SEGMENTS = 24


def build_dome():
    vertices = []   # (x, y, z)
    uvs = []
    for ring in range(RINGS + 1):
        # from just below the horizon (-6 deg) to the zenith
        pitch = math.radians(-6.0 + (96.0 * ring / RINGS))
        z = math.sin(pitch) * RADIUS
        r = math.cos(pitch) * RADIUS
        for seg in range(SEGMENTS + 1):
            yaw = 2.0 * math.pi * seg / SEGMENTS
            vertices.append((math.cos(yaw) * r, math.sin(yaw) * r, z))
            uvs.append((seg / SEGMENTS, ring / RINGS))
    faces = []
    for ring in range(RINGS):
        for seg in range(SEGMENTS):
            a = ring * (SEGMENTS + 1) + seg
            b = a + 1
            c = a + SEGMENTS + 1
            d = c + 1
            # wound inward (viewer sits inside the dome)
            faces.append((a, c, b))
            faces.append((b, c, d))
    return vertices, uvs, faces


def make_textures(tex_dir):
    from PIL import Image, ImageDraw, ImageFilter
    os.makedirs(tex_dir, exist_ok=True)
    presets = {
        "sky_day": ((118, 168, 214), (196, 222, 240), 26),
        "sky_evening": ((208, 122, 74), (244, 208, 160), 18),
        "sky_night": ((10, 14, 30), (36, 44, 72), 0),
    }
    rng = random.Random(7)
    for name, (top, horizon, clouds) in presets.items():
        img = Image.new("RGB", (512, 256))
        for y in range(256):
            t = y / 255.0
            row = tuple(int(top[c] + (horizon[c] - top[c]) * t) for c in range(3))
            for x in range(512):
                img.putpixel((x, y), row)
        if clouds:
            layer = Image.new("L", (512, 256), 0)
            draw = ImageDraw.Draw(layer)
            for _ in range(clouds):
                cx, cy = rng.randint(0, 511), rng.randint(90, 220)
                w, h = rng.randint(30, 90), rng.randint(6, 16)
                draw.ellipse((cx - w, cy - h, cx + w, cy + h), fill=rng.randint(60, 130))
            layer = layer.filter(ImageFilter.GaussianBlur(6))
            white = Image.new("RGB", (512, 256), (250, 250, 252))
            img = Image.composite(white, img, layer)
        if name == "sky_night":
            draw = ImageDraw.Draw(img)
            for _ in range(140):
                x, y = rng.randint(0, 511), rng.randint(0, 160)
                draw.point((x, y), fill=(200 + rng.randint(0, 55),) * 3)
        img.save(os.path.join(tex_dir, name + ".png"))
    Image.new("L", (8, 8), 255).save(os.path.join(tex_dir, "sky_illum.png"))


def write(out_dir):
    os.makedirs(out_dir, exist_ok=True)
    make_textures(os.path.join(out_dir, "textures"))
    vertices, uvs, faces = build_dome()

    ase_path = os.path.join(out_dir, "sky.ase")
    with open(ase_path, "w") as out:
        out.write("*3DSMAX_ASCIIEXPORT\t200\n")
        out.write('*COMMENT "sky dome generated by tools/pes21_import"\n')
        out.write("*SCENE {\n\t*SCENE_FILENAME \"sky\"\n")
        out.write("\t*SCENE_FIRSTFRAME 0\n\t*SCENE_LASTFRAME 100\n")
        out.write("\t*SCENE_FRAMESPEED 30\n\t*SCENE_TICKSPERFRAME 160\n")
        out.write("\t*SCENE_BACKGROUND_STATIC 0.000\t0.000\t0.000\n")
        out.write("\t*SCENE_AMBIENT_STATIC 0.000\t0.000\t0.000\n}\n")
        out.write("*MATERIAL_LIST {\n\t*MATERIAL_COUNT 1\n\t*MATERIAL 0 {\n")
        out.write('\t\t*MATERIAL_NAME "sky"\n\t\t*MATERIAL_CLASS "Standard"\n')
        out.write("\t\t*MATERIAL_AMBIENT 1.000\t1.000\t1.000\n")
        out.write("\t\t*MATERIAL_DIFFUSE 1.000\t1.000\t1.000\n")
        out.write("\t\t*MATERIAL_SPECULAR 0.000\t0.000\t0.000\n")
        out.write("\t\t*MATERIAL_SHINE 0.010\n")
        out.write("\t\t*MATERIAL_SHINESTRENGTH 0.0\n")
        out.write("\t\t*MATERIAL_SELFILLUM 1.0\n")
        out.write("\t\t*MATERIAL_SHADING Blinn\n")
        out.write("\t\t*MAP_DIFFUSE {\n\t\t\t*MAP_NAME \"sky\"\n")
        out.write('\t\t\t*MAP_CLASS "Bitmap"\n')
        out.write('\t\t\t*BITMAP "media/objects/stadiums/sky/textures/sky_day.png"\n')
        out.write("\t\t\t*MAP_TYPE Screen\n\t\t}\n")
        # a white self-illumination map marks the dome fully emissive, so the
        # deferred shaders show the sky texture unshaded (see simple.frag)
        out.write("\t\t*MAP_SELFILLUM {\n\t\t\t*MAP_NAME \"skyillum\"\n")
        out.write('\t\t\t*MAP_CLASS "Bitmap"\n')
        out.write('\t\t\t*BITMAP "media/objects/stadiums/sky/textures/sky_illum.png"\n')
        out.write("\t\t\t*MAP_TYPE Screen\n\t\t}\n\t}\n}\n")
        out.write("*GEOMOBJECT {\n")
        out.write('\t*NODE_NAME "sky"\n')
        out.write("\t*NODE_TM {\n\t\t*NODE_NAME \"sky\"\n")
        out.write("\t\t*INHERIT_POS 0 0 0\n\t\t*INHERIT_ROT 0 0 0\n\t\t*INHERIT_SCL 0 0 0\n")
        out.write("\t\t*TM_ROW0 1.0\t0.0\t0.0\n\t\t*TM_ROW1 0.0\t1.0\t0.0\n")
        out.write("\t\t*TM_ROW2 0.0\t0.0\t1.0\n\t\t*TM_ROW3 0.0\t0.0\t0.0\n\t}\n")
        out.write("\t*MESH {\n")
        out.write("\t\t*MESH_NUMVERTEX %d\n" % len(vertices))
        out.write("\t\t*MESH_NUMFACES %d\n" % len(faces))
        out.write("\t\t*MESH_VERTEX_LIST {\n")
        for i, (x, y, z) in enumerate(vertices):
            out.write("\t\t\t*MESH_VERTEX %d\t%.3f\t%.3f\t%.3f\n" % (i, x, y, z))
        out.write("\t\t}\n\t\t*MESH_FACE_LIST {\n")
        for i, (a, b, c) in enumerate(faces):
            out.write("\t\t\t*MESH_FACE %d: A: %d B: %d C: %d AB: 1 BC: 1 CA: 1 "
                      "*MESH_SMOOTHING 1 *MESH_MTLID 0\n" % (i, a, b, c))
        out.write("\t\t}\n")
        out.write("\t\t*MESH_NUMTVERTEX %d\n" % len(uvs))
        out.write("\t\t*MESH_TVERTLIST {\n")
        for i, (u, v) in enumerate(uvs):
            out.write("\t\t\t*MESH_TVERT %d\t%.4f\t%.4f\t0.0\n" % (i, u, v))
        out.write("\t\t}\n")
        out.write("\t\t*MESH_NUMTVFACES %d\n" % len(faces))
        out.write("\t\t*MESH_TFACELIST {\n")
        for i, (a, b, c) in enumerate(faces):
            out.write("\t\t\t*MESH_TFACE %d\t%d\t%d\t%d\n" % (i, a, b, c))
        out.write("\t\t}\n")
        # straight-down normals keep the sun's diffuse term at zero, so the
        # dome shows its texture at ambient brightness only (fake unlit)
        ase_util.write_mesh_normals(out, vertices, faces,
                                    constant=(0.0, 0.0, -1.0))
        out.write("\t}\n")
        out.write("\t*PROP_MOTIONBLUR 0\n\t*PROP_CASTSHADOW 0\n")
        out.write("\t*PROP_RECVSHADOW 0\n\t*MATERIAL_REF 0\n}\n")

    open(os.path.join(out_dir, "sky.object"), "w").write(
        "<object>\n\n\t<geometry>\n"
        "\t\t<filename>sky.ase</filename>\n"
        "\t\t<name>sky</name>\n"
        "\t\t<position>0, 0, -20</position>\n"
        "\t\t<rotation>0, 0, 0, 0</rotation>\n"
        "\t\t<properties>\n\t\t\t<physicable>false</physicable>\n"
        "\t\t\t<movable>false</movable>\n\t\t</properties>\n"
        "\t</geometry>\n\n</object>\n")


if __name__ == "__main__":
    write(sys.argv[1] if len(sys.argv) > 1 else
          "../../data/media/objects/stadiums/sky")
    print("sky dome written")
