"""Renders a replay-wipe transition as an editable alpha frame sequence.

Broadcast football brackets its replays with a short stinger (see
docs/PRESENTATION_SPEC.md section 2): a badge glows up out of the outgoing
shot, then a jagged bolt of light tears across frame and the destination shot
is revealed behind it. The engine has no video decoder and packs hold simple
editable formats, so the stinger ships as numbered RGBA PNG frames plus a
plain-text manifest that src/utils/wipeoverlay.cpp reads.

  python3 wipe_gen.py <out_dir> [--frames 45] [--width 640] [--height 360]

Swap the PNGs for hand-drawn or rendered ones and the engine plays those
instead; only the manifest has to keep matching.
"""

import argparse
import math
import os


def _bolt_x(y, width, progress):
    """Horizontal position of the bolt's leading edge at row y (0..1)."""
    # a diagonal sweep with a few kinks, so the edge reads as a lightning crack
    kink = (math.sin(y * 11.0) * 0.035 + math.sin(y * 23.0 + 1.7) * 0.02)
    return (progress * 1.5 - 0.25 + (y - 0.5) * 0.35 + kink) * width


def render(out_dir, frames, width, height):
    from PIL import Image, ImageDraw, ImageFilter
    os.makedirs(out_dir, exist_ok=True)

    badge_frames = max(1, int(frames * 0.45))
    for index in range(frames):
        img = Image.new("RGBA", (width, height), (0, 0, 0, 0))
        draw = ImageDraw.Draw(img)

        if index < badge_frames:
            # stage A: the badge assembles over a deepening violet glow
            t = index / float(badge_frames)
            glow = int(200 * min(1.0, t * 1.6))
            draw.rectangle((0, 0, width, height), fill=(38, 12, 58, glow))
            radius = int(min(width, height) * (0.10 + 0.06 * t))
            cx, cy = width // 2, height // 2
            ring = int(255 * min(1.0, t * 2.0))
            for step, alpha in ((0, ring), (6, ring // 2), (12, ring // 4)):
                draw.ellipse((cx - radius - step, cy - radius - step,
                              cx + radius + step, cy + radius + step),
                             outline=(226, 214, 255, alpha), width=3)
            inner = int(radius * 0.55)
            draw.ellipse((cx - inner, cy - inner, cx + inner, cy + inner),
                         fill=(150, 96, 226, int(220 * t)))
        else:
            # stage B: the bolt sweeps across, revealing what is behind it
            t = (index - badge_frames) / float(max(1, frames - badge_frames))
            rows = 64
            for row in range(rows):
                y0 = height * row / rows
                y1 = height * (row + 1) / rows
                edge = min(max(_bolt_x(row / float(rows), width, t), 0.0), float(width))
                # everything the bolt has passed is clear; ahead of it stays
                # covered by the fading violet field
                if edge < width:
                    draw.rectangle((edge, y0, width, y1),
                                   fill=(38, 12, 58, int(200 * (1.0 - t * 0.55))))
                draw.line((edge, y0, edge, y1), fill=(255, 214, 140, 255), width=7)
                draw.line((edge, y0, edge, y1), fill=(255, 255, 255, 255), width=3)
            img = img.filter(ImageFilter.GaussianBlur(1.2))

        img.save(os.path.join(out_dir, "wipe_%03d.png" % index))

    with open(os.path.join(out_dir, "wipe.txt"), "w") as manifest:
        manifest.write("# replay stinger, generated by tools/pes21_import/wipe_gen.py\n")
        manifest.write("fps 30\n")
        manifest.write("frames wipe_%03d.png\n")
        manifest.write("count %d\n" % frames)
        manifest.write("first 0\n")
    return frames


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("out_dir")
    parser.add_argument("--frames", type=int, default=45)
    parser.add_argument("--width", type=int, default=640)
    parser.add_argument("--height", type=int, default=360)
    args = parser.parse_args()
    count = render(args.out_dir, args.frames, args.width, args.height)
    print("wrote %d wipe frames to %s" % (count, args.out_dir))


if __name__ == "__main__":
    main()
